### ISSUE TITLE
responsive problem with bottom sheet

### ISSUE THREAD

**Issue by omeralpi** [sarjdev/front-end#3]
Hello, 

I've noticed some responsive issues. 

If the screen height is too short or too tall, the bottom sheet behaves differently.

1. ![Screenshot 2024-04-02 at 21 07 43](https://github.com/sarjdev/front-end/assets/19254700/74536d00-ce9d-496b-b857-4cde2371b490)

2. ![Screenshot 2024-04-02 at 20 54 40](https://github.com/sarjdev/front-end/assets/19254700/b5073b32-5a6f-46af-bfb3-76217e0e65ea)

**Comment by MhmtMutlu** [comment]
Hi @omeralpi,

We appreciate you reviewing and contributing to our app.
