### ISSUE TITLE
Pop-up visibility issue when clicking near the top of the page and responsive design issue

### ISSUE THREAD

**Issue by zehrabekar** [sarjdev/front-end#6]
If the clicked location is near the top of the page, the pop-up opens upwards and is not fully visible. The content of the pop-up cannot be fully seen without scrolling up. The pop-up should open in a position where its content is fully visible.

![Screenshot from 2024-08-03 17-31-38](https://github.com/user-attachments/assets/87cc3184-1b72-4b85-8a4b-e9811f46fc4d)

When the page width is 900 px or more, clicking on a location opens a pop-up.

![Screenshot from 2024-08-03 18-57-10](https://github.com/user-attachments/assets/ddebe684-137a-41e6-acb6-2e5ba8fb1797)

When the page width is reduced to below 900 px, the pop-up closes.

![Screenshot from 2024-08-03 18-57-18](https://github.com/user-attachments/assets/ecbdf55f-a26f-4e86-85bf-c56fff2c0737)

Clicking again to view the location details opens a "bottom sheet" instead of a pop-up.

![Screenshot from 2024-08-03 18-57-46](https://github.com/user-attachments/assets/13b93d11-2a59-41be-be99-3cabee77b6f3) 

There is no transition between the pop-up and "bottom sheet"; the pop-up closes, and clicking again is required to open the "bottom sheet."

When the page width is 899 px or less, clicking on a location opens it as a "bottom sheet." When the page width is increased to 899 px or more, the "bottom sheet" remains and does not switch back to a pop-up.

![Screenshot from 2024-08-03 18-57-52](https://github.com/user-attachments/assets/3f273de2-e06d-4fe5-bd8a-874bb038e71a)

**Comment by MhmtMutlu** [comment]
@zehrabekar, we sincerely appreciate your interest and the time you've dedicated to our project. The request concerning the location where the popup opens is on our agenda, and we are committed to addressing it promptly. Regarding the issue you observed when switching between responsive and web views, we do not currently have plans to address this, as it falls outside of what we consider typical user behavior.

**Comment by zehrabekar** [comment]
Thank you, wishing you continued success with the project.
